dist: xenial
language: go
go:
  - stable
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
    - ./packer_cache
env:
  global:
    - GOPROXY=https://proxy.golang.org
addons:
  apt:
    packages:
      - kpartx
      - qemu-user-static
install:
  - ./build-packer.sh
script:
  - sudo ./packer build arch-raspi.json
  - ls -la
