dist: xenial
language: go
go:
  - stable
cache:
  directories:
    - $GOPATH
    - ./packer_cache
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
addons:
  apt:
    packages:
      - kpartx
      - qemu-user-static
install:
  - ./build-packer.sh
script:
  - sudo ./packer build arch-raspi.json
  - ls -la
