sudo: false
dist: xenial
language: go
go:
  - "1.11.x"
cache:
  directories:
    - ~/.go
addons:
  apt:
    packages:
      - kpartx
      - qemu-user-static
install:
  - ./build-packer.sh
script:
  - ./packer build arch-raspi.json
after_success:
  - ls -la
