name: build

on: [push]

env:
  PACKER_VERSION: 1.4.4
  LIBARCHIVE_VERSION: 3.4.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # CODE
    - uses: actions/checkout@v2
    # TOOLS
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    # Caches
    - name: Cache libarchive build
      uses: actions/cache@v1
      with:
        path: ./libarchive-${{env.LIBARCHIVE_VERSION}}
        key: libarchive-${{env.LIBARCHIVE_VERSION}}-1
    - name: Cache images
      uses: actions/cache@v1
      with:
        path: ./packer_cache
        key: ./packer_cache-1
    - name: Cache go mod
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-mod-1
    - name: Cache go build
      uses: actions/cache@v1
      with:
        path: ~/.cache/go-build
        key: go-build-1

    # Installs
    - name: install libarchive
      shell: bash
      run: |
        sudo ./build-bsdtar.sh $LIBARCHIVE_VERSION
    - name: install deps
      shell: bash
      run: |
        sudo apt install qemu-user-static util-linux gdisk e2fsprogs
    - name: install packer and plugins
      shell: bash
      run: |
        ./build-packer.sh ${{ env.PACKER_VERSION }}

    # Build
    - name: run packer
      shell: bash
      run: |
        sudo ./packer build arch-raspi.json
        ls -la
        zip -r9 --display-dots raspberry-pi3.img.zip raspberry-pi3.img

    # Upload
    - uses: actions/upload-artifact@v1
      with:
        name: raspberry-pi3.img.zip
        path: raspberry-pi3.img.zip
