name: build

on: [push]

env:
  PACKER_VERSION: 1.5.5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1' # The Go version to download (if necessary) and use.
    - name: install packer + plugins + deps
      run: |
        sudo apt install kpartx qemu-user-static
        ./build-packer.sh ${{ env.PACKER_VERSION }}
