name: build

on: [push]

env:
  PACKER_VERSION: 1.5.5
  ARM_BUILDER_VERSION: 0.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: |
        sudo apt install kpartx qemu-user-static
    - name: install packer and plugins
      run: |
        ./build-packer.sh ${{ env.PACKER_VERSION }} ${{ env.ARM_BUILDER_VERSION }}
    - name: run packer
      run: |
        sudo ./packer build arch-raspi.json
        ls -la
