name: build

on: [push]

env:
  PACKER_VERSION: 1.4.4
  LIBARCHIVE_VERSION: 3.4.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
    - name: Cache libarchive build
      uses: actions/cache@v1
      with:
        path: ./libarchive-${{env.LIBARCHIVE_VERSION}}
        key: libarchive-${{env.LIBARCHIVE_VERSION}}
    - name: Cache images
      uses: actions/cache@v1
      with:
        path: ./packer_cache
        key: ./packer_cache-1
    - name: install libarchive
      run: |
        sudo ./build-bsdtar.sh $LIBARCHIVE_VERSION
    - name: install deps
      run: |
        sudo apt install qemu-user-static util-linux gdisk e2fsprogs
    - name: install packer and plugins
      run: |
        ./build-packer.sh ${{ env.PACKER_VERSION }}
    - name: run packer
      run: |
        sudo ./packer build arch-raspi.json
        ls -la
        zip -r9 --display-dots raspberry-pi3.img.zip raspberry-pi3.img
    - uses: actions/upload-artifact@v1
      with:
        name: raspberry-pi3.img.zip
        path: raspberry-pi3.img.zip
